name: Code Coverage
permissions:
  contents: read
on: [push, pull_request]
jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - run: go test -race -coverprofile=cover.out -covermode=atomic ./codec/... ./internal/...
      - uses: codecov/codecov-action@v3
        with:
          file: cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true