name: Go Vulnerability Check
permissions:
  contents: read
on: [push, pull_request]
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: echo "$HOME/go/bin" >> $GITHUB_PATH
      - run: govulncheck ./...
